name: ESLint
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npx eslint ./js/script.js
      - name: Run StyleLint
        run: npx stylelint ./css/style.css
